version: "3.7"
services:
  template:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - shopping-db
  shopping-db:
    image: postgres:9.4
    ports:
      - "5434:5434"
    volumes:
      - type: volume
        source: dbdata
        target: "/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password
  shopping-pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "9001:80"
    volumes:
      - type: volume
        source: pgadmindata
        target: "/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
volumes:
  dbdata:
  pgadmindata:

